// <auto-generated />
namespace Bounds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addfixpointvaluecolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addfixpointvaluecolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201707291437075_add fix point value column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
