// <auto-generated />
namespace Bounds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class auth表增加b_Show字段 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auth表增加b_Show字段));
        
        string IMigrationMetadata.Id
        {
            get { return "201709241200472_auth表增加b_Show字段"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
