// <auto-generated />
namespace Bounds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeb_User_idtob_Role_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeb_User_idtob_Role_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201707221510205_change b_User_id to b_Role_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
