// <auto-generated />
namespace Bounds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addevent_libandpointandpoint_eventandevent_member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addevent_libandpointandpoint_eventandevent_member));
        
        string IMigrationMetadata.Id
        {
            get { return "201707271511590_add event_lib and point and point_event and event_member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
