// <auto-generated />
namespace Bounds.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_work_age_point_to_attencefix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_work_age_point_to_attencefix));
        
        string IMigrationMetadata.Id
        {
            get { return "201803091549246_add_work_age_point_to_attencefix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
